# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ultra/ultra.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra || ORIG_REF_NAME==ultra} -quiet] -quiet

# IP: bd/ultra/ip/ultra_clk_wiz_0_0/ultra_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra_clk_wiz_0_0 || ORIG_REF_NAME==ultra_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ultra/ip/ultra_ps_e_0_0/ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra_ps_e_0_0 || ORIG_REF_NAME==ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ultra/ip/ultra_psr_clk0_150_0/ultra_psr_clk0_150_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra_psr_clk0_150_0 || ORIG_REF_NAME==ultra_psr_clk0_150_0} -quiet] -quiet

# IP: bd/ultra/ip/ultra_psr_clk1_300_0/ultra_psr_clk1_300_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra_psr_clk1_300_0 || ORIG_REF_NAME==ultra_psr_clk1_300_0} -quiet] -quiet

# IP: bd/ultra/ip/ultra_psr_clk2_75_0/ultra_psr_clk2_75_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra_psr_clk2_75_0 || ORIG_REF_NAME==ultra_psr_clk2_75_0} -quiet] -quiet

# IP: bd/ultra/ip/ultra_psr_clk3_100_0/ultra_psr_clk3_100_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra_psr_clk3_100_0 || ORIG_REF_NAME==ultra_psr_clk3_100_0} -quiet] -quiet

# IP: bd/ultra/ip/ultra_psr_clk4_200_0/ultra_psr_clk4_200_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra_psr_clk4_200_0 || ORIG_REF_NAME==ultra_psr_clk4_200_0} -quiet] -quiet

# IP: bd/ultra/ip/ultra_psr_clk5_400_0/ultra_psr_clk5_400_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra_psr_clk5_400_0 || ORIG_REF_NAME==ultra_psr_clk5_400_0} -quiet] -quiet

# IP: bd/ultra/ip/ultra_psr_clk6_600_0/ultra_psr_clk6_600_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra_psr_clk6_600_0 || ORIG_REF_NAME==ultra_psr_clk6_600_0} -quiet] -quiet

# IP: bd/ultra/ip/ultra_xlconcat_0_0/ultra_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra_xlconcat_0_0 || ORIG_REF_NAME==ultra_xlconcat_0_0} -quiet] -quiet

# IP: bd/ultra/ip/ultra_xlconcat_1_0/ultra_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra_xlconcat_1_0 || ORIG_REF_NAME==ultra_xlconcat_1_0} -quiet] -quiet

# IP: bd/ultra/ip/ultra_xlconstant_0_0/ultra_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra_xlconstant_0_0 || ORIG_REF_NAME==ultra_xlconstant_0_0} -quiet] -quiet

# XDC: bd/ultra/ultra_ooc.xdc
