# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xczu3eg-sbva484-1-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.cache/wt [current_project]
set_property parent.project_path /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/hdl/ultra_wrapper.v
add_files /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ultra.bd
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_clk_wiz_0_0/ultra_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_clk_wiz_0_0/ultra_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_clk_wiz_0_0/ultra_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_ps_e_0_0/ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_ps_e_0_0/ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk0_150_0/ultra_psr_clk0_150_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk0_150_0/ultra_psr_clk0_150_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk0_150_0/ultra_psr_clk0_150_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk1_300_0/ultra_psr_clk1_300_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk1_300_0/ultra_psr_clk1_300_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk1_300_0/ultra_psr_clk1_300_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk2_75_0/ultra_psr_clk2_75_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk2_75_0/ultra_psr_clk2_75_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk2_75_0/ultra_psr_clk2_75_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk3_100_0/ultra_psr_clk3_100_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk3_100_0/ultra_psr_clk3_100_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk3_100_0/ultra_psr_clk3_100_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk4_200_0/ultra_psr_clk4_200_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk4_200_0/ultra_psr_clk4_200_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk4_200_0/ultra_psr_clk4_200_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk5_400_0/ultra_psr_clk5_400_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk5_400_0/ultra_psr_clk5_400_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk5_400_0/ultra_psr_clk5_400_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk6_600_0/ultra_psr_clk6_600_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk6_600_0/ultra_psr_clk6_600_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_psr_clk6_600_0/ultra_psr_clk6_600_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ultra_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ultra_wrapper -part xczu3eg-sbva484-1-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ultra_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ultra_wrapper_utilization_synth.rpt -pb ultra_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
