# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_clk_wiz_0_0/ultra_clk_wiz_0_0.xci
# IP: The module: 'ultra_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_clk_wiz_0_0/ultra_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_clk_wiz_0_0/ultra_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_clk_wiz_0_0/ultra_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_clk_wiz_0_0/ultra_clk_wiz_0_0.xci
# IP: The module: 'ultra_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_clk_wiz_0_0/ultra_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_clk_wiz_0_0/ultra_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /mnt/500GB/home/steve/TCN/ultra/ultra/ultra.srcs/sources_1/bd/ultra/ip/ultra_clk_wiz_0_0/ultra_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
